version: '2.1'
services:

# media server
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest   
    restart: unless-stopped
    network_mode: host
    ports:
      - 8096:8096    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=etc/utc
    volumes:
      - /var/config/jellyfin:/config
      - /mnt/sdb1/media/movies:/movies
      - /mnt/sdb1/media/tv:/tv
      - /mnt/sdb1/media/dvr:/dvr
      - /var/config/threadfin/conf/data:/xml #XMLTV from Xteve
    healthcheck:
          test: curl -fsS curl -i http://localhost:8096/health
          start_period: 180s
          timeout: 10s
          interval: 60s
          retries: 3
    labels:
      - autoheal=true
            
# torrent client
  qbittorrent:
    image: linuxserver/qbittorrent:latest   
    network_mode: host
    container_name: qbittorrent
    ports:
      - 8080:8080
      - 6881:6881
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /var/config/qbittorrent:/config
      - /mnt/sdb1/downloads:/sdb1/downloads
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:8080
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

# movie collection manager
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest 
    network_mode: host
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/radarr:/config
      - /mnt/sdb1:/sdb1 
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:7878
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

# tv collection manager
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest 
    network_mode: host
    ports:
      - 8989:8989    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/sonarr:/config
      - /mnt/sdb1:/sdb1
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:8989
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

# audiobooks collection manager
  readarr:
    container_name: readarr
    image: linuxserver/readarr:nightly   
    network_mode: host
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/readarr:/config
      - /mnt/sdb1:/sdb1
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:8787
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

#indexer manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/prowlarr:/config
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:9696
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

# indexer proxy
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: host
    ports:
      - 8191:8191
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:8191
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

# audiobook server
  audiobookshelf:
    container_name: audiobookshelf    
    image: ghcr.io/advplyr/audiobookshelf:latest
    network_mode: host
    ports:
      - 80:80
    volumes:
      - /mnt/sdb1/media/audiobooks:/audiobooks
      - /mnt/sdb1/media/podcasts:/podcasts
      - /var/config/audiobookshelf:/config
      - /var/config/audiobookshelf/metadata:/metadata
    healthcheck:
      test: curl -fsS http://localhost:80
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

# IPTV tuner for Plex
  threadfin:
    container_name: threadfin
    image: fyb3roptik/threadfin:latest
    network_mode: host
    ports:
      - 34400:34400  
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=etc/utc
    volumes:
      - /var/config/threadfin/conf:/home/threadfin/conf
      - /var/tmp/threadfin:/tmp/threadfin
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:34400/web
      start_period: 420s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true

# home automation
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    network_mode: host
    ports:
      - 8123:8123
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /mnt/sdb1/media/:/media
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: curl -fsS http://127.0.0.1:8123
      start_period: 120s
      timeout: 10s
      interval: 60s
      retries: 3
    labels:
      - autoheal=true


# auto restart containers
  autoheal:
    container_name: autoheal
    deploy:
      replicas: 1
    image: willfarrell/autoheal:latest
    network_mode: none
    environment:
      - AUTOHEAL_START_PERIOD=300
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
