version: '1.1'
services:
  # VPN
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qbittorrent webUI
      - 6881:6881/tcp # qbittorrent torrent port tcp
      - 6881:6881/udp # qbittorrent torrent port udp
      - 7878:7878 # radarr
      - 8989:8989 # sonarr
      - 8787:8787 # readarr
      - 9696:9696 # prowlarr
      - 34400:34400/tcp # xteve
      - 8191:8191 # flaresolverr
    volumes:
      - /var/config/gluetun:/config
    environment:
      - VPNSP=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=4379779465932262
      - OPENVPN_CIPHERS=AES-256-GCM
      - OWNED=yes
      - SERVER_COUNTRIES=UK
      - TZ=Europe/London
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
    restart: unless-stopped

  # reverse proxy
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: "service:gluetun" # VPN
    environment:
      - TS_AUTHKEY=tskey-client-kLvpKstMQV11CNTRL-MPaCiyoSBkJwyjL4Ebc8kJ3zc2p1YeuaW
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=plexpi
    volumes:
      - /var/config/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy

  # media server
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    network_mode: "service:tailscale" # VPN
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=etc/utc
    volumes:
      - /var/config/jellyfin:/config
      - /mnt/sdb1/media/movies:/movies
      - /mnt/sdb1/media/tv:/tv
      - /mnt/sdb1/media/dvr:/dvr
      - /var/config/threadfin/conf/data:/xml # XMLTV from Xteve
    healthcheck:
      test: curl -fsS curl -i http://localhost:8096/health || exit 1
      start_period: 60s
      timeout: 10s
      interval: 5s
      retries: 3
    depends_on:
      tailscale:
        condition: service_healthy

  # torrent client
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    network_mode: "service:tailscale" # VPN
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /var/config/qbittorrent:/config
      - /mnt/sdb1/downloads:/sdb1/downloads
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:8080 || exit 1
      start_period: 90s
      timeout: 10s
      interval: 5s
      retries: 3
    depends_on:
      tailscale:
        condition: service_healthy

  # movie collection manager
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/radarr:/config
      - /mnt/sdb1:/sdb1
    network_mode: "service:tailscale" # VPN
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:7878 || exit 1
      start_period: 60s
      timeout: 10s
      interval: 5s
      retries: 3
    depends_on:
      tailscale:
        condition: service_healthy

  # tv collection manager
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: "service:tailscale" # VPN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/sonarr:/config
      - /mnt/sdb1:/sdb1
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost1:8989 || exit 1
      timeout: 10s
      interval: 5s
      retries: 3
    depends_on:
      tailscale:
        condition: service_healthy

  # audiobooks collection manager
  readarr:
    container_name: readarr
    image: linuxserver/readarr:nightly 
    network_mode: "service:tailscale" # VPN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/readarr:/config
      - /mnt/sdb1:/sdb1
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://localhost:8787 || exit 1
      start_period: 90s
      timeout: 20s
      interval: 20s
      retries: 3
    depends_on:
      tailscale:
        condition: service_healthy

  # indexer manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/config/prowlarr:/config
    network_mode: "service:tailscale" # VPN
    restart: unless-stopped
    healthcheck:
      test: curl -fSs http://
