version: '1.1'
services:

#VPN
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080/tcp # qBittorrent
      - 34400:34400/tcp # xteve
    volumes:
      - /var/config/gluetun:/config
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=4379779465932262
      - OPENVPN_PASSWORD=4379779465932262
      - OPENVPN_CIPHERS=AES-256-GCM
    restart: unless-stopped
    
#Torrent Client
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    network_mode: "service:gluetun"
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /var/config/qbittorrent:/config
      - /var/tmp/downloads:/downloads
    restart: unless-stopped
    healthcheck:
      test: curl -fSs https://google.com || exit 1
      start_period: 90s
      timeout: 10s
      interval: 5s
      retries: 3
    # cpu_percent: 50
    #mem_limit: 1500M
    #mem_reservation: 1300M

#Media Server
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /var/config/plex:/config
      - /var/media/tv:/tv
      - /var/media/movies:/movies
    network_mode: host
    ports:
      - 32400:32400
    restart: unless-stopped
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      start_period: 60s
      timeout: 10s
      interval: 5s
      retries: 3
    # cpu_percent: 50
    #mem_limit: 1500M
    #mem_reservation: 1300M
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/sda1/docker/radarr:/config
      - /mnt/sda1/movies:/movies #optional
      - /mnt/sda1/downloads:/downloads #optional
    network_mode: "service:gluetun"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/sda1/docker/sonarr:/config
      - /mnt/sda1/tv:/tv #optional
      - /mnt/sda1/downloads:/downloads #optional
    network_mode: "service:gluetun"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/data:/config
    network_mode: "service:gluetun"
    restart: unless-stopped
